//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraoDoiDo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        private int id;
        private int idNguoiDang;
        private string ten;
        private string linkAnhBia;
        private string loai;
        private string soLuong;
        private string soLuongDaBan;
        private string giaGoc;
        private string giaBan;
        private string phiShip;
        private string trangThai;
        private string noiBan;
        private string xuatXu;
        private string ngayMua;
        private string moTaChung;
        private string phanTramMoi;
        private string luotXem;
        private int idNguoiMua;
        private QuanLyDonHang quanLyDonHang;
        public SanPham(int id, int idNguoiDang, string ten, string linkAnhBia, string loai, string soLuong, string soLuongDaBan, string giaGoc, string giaBan, string phiShip, string trangThai, string noiBan, string xuatXu, string ngayMua, string moTaChung, string phanTramMoi, string luotXem, int idNguoiMua)
        {
            this.id = id;
            this.ten = ten;
            this.linkAnhBia = linkAnhBia;
            this.loai = loai;
            this.soLuong = soLuong;
            this.soLuongDaBan = soLuongDaBan;
            this.giaGoc = giaGoc;
            this.giaBan = giaBan;
            this.phiShip = phiShip;
            this.trangThai = trangThai;
            this.noiBan = noiBan;
            this.xuatXu = xuatXu;
            this.ngayMua = ngayMua;
            this.moTaChung = moTaChung;
            this.phanTramMoi = phanTramMoi;
            this.idNguoiDang = idNguoiDang;
            this.luotXem = luotXem;
            this.idNguoiMua = idNguoiMua;
        }
        public SanPham()
        {
            this.DanhMucYeuThiches = new HashSet<DanhMucYeuThich>();
            this.GioHangs = new HashSet<GioHang>();
            this.MoTaAnhSanPhams = new HashSet<MoTaAnhSanPham>();
            this.QuanLyDonHangs = new HashSet<QuanLyDonHang>();
            this.TrangThaiDonHangs = new HashSet<TrangThaiDonHang>();
        }

        public int IdSanPham { get => id; set => id = value; }
        public int IdNguoiDang { get => idNguoiMua; set => idNguoiMua = value; }
        public string Ten { get => ten; set => ten = value; }
        public string LinkAnhBia { get => linkAnhBia; set => linkAnhBia = value; }
        public string Loai { get => loai; set => loai = value; }
        public string SoLuong { get => soLuong; set => soLuong = value; }
        public string SoLuongDaBan { get => soLuongDaBan; set => soLuongDaBan = value; }
        public string GiaGoc { get => giaGoc; set => giaGoc = value; }
        public string GiaBan { get => giaBan; set => giaBan = value; }
        public string PhiShip { get => phiShip; set => phiShip = value; }
        public string TrangThai { get => trangThai; set => trangThai = value; }
        public string NoiBan { get => noiBan; set => noiBan = value; }
        public string XuatXu { get => xuatXu; set => xuatXu = value; }
        public string NgayMua { get => ngayMua; set => ngayMua = value; }
        public string PhanTramMoi { get => phanTramMoi; set => phanTramMoi = value; }
        public string MoTaChung { get => moTaChung; set => moTaChung = value; }
        public string SoLuotXem { get => luotXem; set => luotXem = value; }
        public QuanLyDonHang QuanLyDonHang { get => quanLyDonHang; set => quanLyDonHang = value; }


        public virtual ICollection<DanhMucYeuThich> DanhMucYeuThiches { get; set; }

        public virtual ICollection<GioHang> GioHangs { get; set; }

        public virtual ICollection<MoTaAnhSanPham> MoTaAnhSanPhams { get; set; }

        public virtual ICollection<QuanLyDonHang> QuanLyDonHangs { get; set; }

        public virtual ICollection<TrangThaiDonHang> TrangThaiDonHangs { get; set; }
    }
}
