//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraoDoiDo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {

        private int idNguoiDung;

        private string tenDangNhap;

        private string matKhau;
        public TaiKhoan() { }
        public TaiKhoan(int idNguoiDung, string tenDangNhap, string matKhau)
        {
            this.IdNguoiDung = idNguoiDung;
            this.TenDangNhap = tenDangNhap;
            this.MatKhau = matKhau;
        }
        
    
        public virtual NguoiDung NguoiDung { get; set; }
        public int IdNguoiDung { get => idNguoiDung; set => idNguoiDung = value; }
        public string TenDangNhap { get => tenDangNhap; set => tenDangNhap = value; }
        public string MatKhau { get => matKhau; set => matKhau = value; }
    }
}
